Improved metadata
RappyBots/Boost-Frontend pull request #3
Opened 2024-02-22 14:13 UTC by holybaechu

2024-02-22 15:08 UTC, holybaechu commented
> and the name/description and especially the url need to be dynamic depending on the page

Going to do that tomorrow with SEO

2024-02-22 15:09 UTC, RappyTV commented
Alright. I'm adding a few commits soon which improve the feature descriptions a bit

2024-02-22 15:25 UTC, RappyTV commented
you can draft prs now btw :)

2024-02-22 17:27 UTC, RappyTV commented
I get this error when trying to build/preview
```
failed to load config from D:\...\Boost-Frontend\vite.config.ts
error when starting preview server:
Error: Dynamic require of "file:///D:/.../Boost-Frontend/node_modules/dotenv/lib/main.js" is not supported
    at file:///D:/.../Boost-Frontend/vite.config.ts.timestamp-1708622757747-2c49a106a5579.mjs:6:9
    at file:///D:/.../Boost-Frontend/vite.config.ts.timestamp-1708622757747-2c49a106a5579.mjs:12:1
```

2024-02-22 17:35 UTC, holybaechu commented
I was going to open vsc but you committed it first xd
also i really hate my school laptop
![image](https://github.com/RappyBots/Boost-Frontend/assets/66154521/50c795ad-83d1-4d14-9cb2-965497802284)

Anyways, Do we need to add some tests?

2024-02-22 17:36 UTC, RappyTV commented
wdym with tests? btw it still does not read the .env file. or where do I have to place it?

2024-02-22 17:40 UTC, holybaechu commented
> wdym with tests?
Something like unit tests.
> btw it still does not read the .env file. or where do I have to place it?
Looks like vite is having a stroke. `bun run build/index.js` should work fine. (run after building the project)

2024-02-22 17:47 UTC, RappyTV commented
> Something like unit tests.

yea idk how to do that but you can set it up if you want. bun worked btw

2024-02-22 17:53 UTC, RappyTV commented
Is it somehow possible to surpress these unnecessary errors when accessing the 404 page: 
![image](https://github.com/RappyBots/Boost-Frontend/assets/72705182/d56492fd-b13f-4642-b610-dac5c0c06f2c)

2024-02-22 17:56 UTC, holybaechu commented
It is possible through error handlers tho.

https://stackoverflow.com/a/75646108

2024-02-23 12:15 UTC, RappyTV commented
alr imma test it when i get home in an hour

2024-02-23 12:25 UTC, RappyTV commented
nope, still not working
also the docs look like this:
![image](https://github.com/RappyBots/Boost-Frontend/assets/72705182/76af15f5-b191-4d17-b86c-a74b3c2b9f62)

2024-02-23 12:47 UTC, holybaechu commented
I just tested it on my iPhone and interestingly, It only happens when there's transition in the element.
So I just removed the transition.

2024-02-23 13:39 UTC, holybaechu commented
Search Engine Optimization is done now.
I didn't enable AMP and disable CSR because it broke some pages. (especially pages with scripts)

Also, This PR is safe to merge now.

2024-02-23 15:39 UTC, RappyTV requested changes
Some things to fix:
1. There is this unnecessary scrollbar at the bottom on mobile and the white line on the right:
![image](https://github.com/RappyBots/Boost-Frontend/assets/72705182/d2479ab1-f9ff-4bdd-a8a2-e5ebb664125b)
2. This white line and cutoff at the bottom:
![image](https://github.com/RappyBots/Boost-Frontend/assets/72705182/1c29a081-bad9-4b71-900d-d49a9d0c5ba9)
3. The button text and hamburger menu text isn't centered:
![image](https://github.com/RappyBots/Boost-Frontend/assets/72705182/4bebd27f-1c73-4ab0-9789-36d87a589531)
The rest turned out beautiful :)

2024-02-23 15:39 UTC, RappyTV commented on src/routes/sitemap.xml/+server.ts
> +const selfURL = "https://boost.rappy.tv";
wrong domain
```suggestion
const selfURL = "https://boost.rappytv.com";
```

2024-02-24 08:10 UTC, RappyTV approved these changes
well I actually meant to just center the text in the buttons but that works aswell. LGTM

2024-02-24 08:11 UTC, merged